from typing import final

def prit(v_: object) -> None: ...

@final
class Colors:
    @staticmethod
    def get_code(color_: str, bg_: bool = True) -> str: ...

@final
class Special:
    @staticmethod
    def reset() -> str: ...
    @staticmethod
    def home() -> str: ...
    @staticmethod
    def clear() -> str: ...

class Canvas:
    @staticmethod
    def clear() -> None: ...
    @staticmethod
    def reset() -> None: ...
    @staticmethod
    def set_background_color(color_: str) -> None: ...
    @staticmethod
    def get_shape() -> tuple[int, int]: ...
    @staticmethod
    def get_width() -> int: ...
    @staticmethod
    def get_height() -> int: ...
    @staticmethod
    def set_width(new_width_: int) -> None: ...
    @staticmethod
    def set_height(new_height_: int) -> None: ...
    @staticmethod
    def draw_rectangle(
        x_: float, y_: float, width_: int, height_: int, color_: str = "red"
    ) -> None: ...
    @staticmethod
    def show(home_: bool = True) -> None: ...
    @staticmethod
    def hello_canvas() -> None: ...
